# Use the PHP 7.3 runtime (BETA) by replacing "php72" below with "php73"
runtime: php72

runtime_config:
    document_root: web
    
handlers:
- url: /(.*\.(gif|png|jpg|ico|html|js|css|swf|xml|md))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|html|js|css|swf|xml|md))

# Defaults to "serve index.php" and "serve public/index.php". Can be used to
# serve a custom PHP front controller (e.g. "serve backend/index.php") or to
# run a long-running PHP script as a worker process (e.g. "php worker.php").
#
# entrypoint: serve index.php

entrypoint: serve index.php
